//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace com.prjteam.HashMe.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("com.prjteam.HashMe.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select text file.
        /// </summary>
        internal static string Main_BtnBrowseClick_Select_text_file {
            get {
                return ResourceManager.GetString("Main_BtnBrowseClick_Select_text_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to txt files (*.txt)|*.txt|csv files (*.csv)|*.csv.
        /// </summary>
        internal static string Main_BtnBrowseClick_txt_files____txt____txt_csv_files____csv____csv {
            get {
                return ResourceManager.GetString("Main_BtnBrowseClick_txt_files____txt____txt_csv_files____csv____csv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copied.
        /// </summary>
        internal static string Main_BtnCopyClick_Copied {
            get {
                return ResourceManager.GetString("Main_BtnCopyClick_Copied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copied to the Clipboard.
        /// </summary>
        internal static string Main_BtnCopyClick_Copied_to_the_Clipboard {
            get {
                return ResourceManager.GetString("Main_BtnCopyClick_Copied_to_the_Clipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string Main_BtnDelTemplClick_Delete {
            get {
                return ResourceManager.GetString("Main_BtnDelTemplClick_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to delete this Template?.
        /// </summary>
        internal static string Main_BtnDelTemplClick_Do_you_want_to_delete_this_Template {
            get {
                return ResourceManager.GetString("Main_BtnDelTemplClick_Do_you_want_to_delete_this_Template", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No template selected..
        /// </summary>
        internal static string Main_BtnDelTemplClick_No_template_selected_ {
            get {
                return ResourceManager.GetString("Main_BtnDelTemplClick_No_template_selected_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string Main_InitComboBox_Error {
            get {
                return ResourceManager.GetString("Main_InitComboBox_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to keep data editable?.
        /// </summary>
        internal static string Program_IsDataEditable_Do_you_want_to_keep_data_editable {
            get {
                return ResourceManager.GetString("Program_IsDataEditable_Do_you_want_to_keep_data_editable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving Template.
        /// </summary>
        internal static string Program_IsDataEditable_Saving_Template {
            get {
                return ResourceManager.GetString("Program_IsDataEditable_Saving_Template", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string Program_LoadTemplate_Error {
            get {
                return ResourceManager.GetString("Program_LoadTemplate_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning! Template file not found. Please check: .
        /// </summary>
        internal static string Program_LoadTemplate_Warning__Template_file_not_found__Please_check {
            get {
                return ResourceManager.GetString("Program_LoadTemplate_Warning__Template_file_not_found__Please_check", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning! XML Template file corrupted. Check syntax..
        /// </summary>
        internal static string Program_LoadTemplate_Warning__XML_Template_file_corrupted__Check_syntax {
            get {
                return ResourceManager.GetString("Program_LoadTemplate_Warning__XML_Template_file_corrupted__Check_syntax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving.
        /// </summary>
        internal static string Program_SaveTemplate_Saving {
            get {
                return ResourceManager.GetString("Program_SaveTemplate_Saving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Template saved.
        /// </summary>
        internal static string Program_SaveTemplate_Template_saved {
            get {
                return ResourceManager.GetString("Program_SaveTemplate_Template_saved", resourceCulture);
            }
        }
    }
}
